import { Inter } from 'next/font/google';

import StyledComponentsRegistry from '@/lib/registry';
import '@/styles/photoswipe.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'DALL-Elyse',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <head>
        <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css' />
      </head>
      <body className={inter.className}>
        <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
      </body>
    </html>
  );
}
