import HeroCanvas from './HeroCanvas';

const Hero = ({ searchText, setSearchText }) => {
  return (
    <section id='brxe-dayjhu' className='brxe-section'>
      <div id='brxe-czscpp' className='brxe-container'>
        <div id='brxe-vnvqxd' data-script-id='vnvqxd' className='brxe-code'>
          <h1 align='center'>
            Meet <span className='rad-color'>DALL-Elyse</span>
          </h1>
          {/* <h2 className='txt-center'><br /></h2> */}
        </div>
        <div id='brxe-udvomq' className='brxe-text-basic'>
          Browse through a collection of imaginative and visually stunning images generated by DALL-E.
        </div>
        <div id='brxe-marcyv' className='brxe-block grid'>
          <form id='brxe-nkbnhw' className='brxe-form news-field news-field-main'>
            <div className='form-group'>
              <input
                id='form-field-e7474a'
                name='form-field-kmhhru'
                type='text'
                value=''
                placeholder='Email'
              />
            </div>
            <div className='form-group submit-button-wrapper'>
              <button type='submit' className='bricks-button bricks-background-primary'>
                <span className='text'>Count me in 🤝</span>
              </button>
            </div>
          </form>
        </div>
      </div>

      <div id='brxe-xbuoqc' className='brxe-block'>
        <HeroCanvas />
        {/* <div id='brxe-merhif' className='brxe-div absolute'></div> */}
      </div>
    </section>
  );
};
export default Hero;
