import { useState } from 'react';

import HeroCanvas from './HeroCanvas';

const Hero = ({ allPosts, searchText, setSearchText, setSearchedResults }) => {
  const [searchTimeout, setSearchTimeout] = useState(null);


  const filterResults = () => {
    setSearchedResults(
      allPosts.filter(
        (post) =>
          post.name.toLowerCase().includes(searchText.toLowerCase()) ||
          post.prompt.toLowerCase().includes(searchText.toLowerCase())
      )
    );
  }
  
  const handleSearchChange = (e) => {
    clearTimeout(searchTimeout);
    setSearchText(e.target.value);
    setSearchTimeout(setTimeout(() => { filterResults(); }, 500));
  };

  return (
    <section id='brxe-dayjhu' className='brxe-section'>
      <div id='brxe-czscpp' className='brxe-container'>
        <div id='brxe-vnvqxd' data-script-id='vnvqxd' className='brxe-code'>
          <h1 align='center'>
            Meet <span className='rad-color'>DALL-Elyse</span>
          </h1>
          {/* <h2 className='txt-center'><br /></h2> */}
        </div>
        <div id='brxe-udvomq' className='brxe-text-basic'>
          Browse through a collection of imaginative and visually stunning images generated by DALL-E.
        </div>
        <div id='brxe-marcyv' className='brxe-block grid'>
          <div id='brxe-nkbnhw' className='brxe-form news-field news-field-main'>
            <div className='form-group'>
              <input
                id='form-field-e7474a'
                name='form-field-kmhhru'
                type='text'
                value={searchText}
                onChange={handleSearchChange}
                placeholder='Search something...'
              />
            </div>
            <div className='form-group submit-button-wrapper'>
              <button className='bricks-button bricks-background-primary' onClick={filterResults}>
                <span className='text'>Search 🔍</span>
              </button>
            </div>
          </div>
        </div>
      </div>

      <div id='brxe-xbuoqc' className='brxe-block'>
        <HeroCanvas />
        {/* <div id='brxe-merhif' className='brxe-div absolute'></div> */}
      </div>
    </section>
  );
};

export default Hero;
